apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dev-shell.fullname" . }}-secrets
data:
  {{- if .Values.s3.access_key }}
  s3_access_key: {{ .Values.s3.access_key | b64enc }}
  {{- end }}
  {{- if .Values.s3.bucket }}
  s3_bucket: {{ .Values.s3.bucket | b64enc }}
  {{- end }}
  {{- if .Values.s3.host }}
  s3_host: {{ .Values.s3.host  | b64enc }}
  {{- end }}
  {{- if .Values.s3.secret_key }}
  s3_secret_key: {{ .Values.s3.secret_key | b64enc }}
  {{- end }}
